# -*- coding: utf-8 -*-
"""Minimal RAG Pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_JfeMexMz4ll0aGcA3N4fuKwCLKyKoMZ
"""

!pip install faiss-cpu sentence-transformers

# Install dependencies (run in Colab once)
# !pip install faiss-cpu sentence-transformers

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

# Step 1: Create knowledge base
documents = [
    "LLMs generate text using next-token probability prediction.",
    "Hallucination occurs when incorrect tokens are assigned high probability.",
    "Exposure bias arises from mismatch between training and inference.",
    "Decoding strategies like beam search can amplify errors.",
    "Lack of grounding leads to fabricated responses."
]

# Step 2: Load embedding model
# 'all-MiniLM-L6-v2' is a great balance of speed and accuracy
model = SentenceTransformer('all-MiniLM-L6-v2')

# Step 3: Convert documents to embeddings and cast to float32
# FAISS requires float32 for most index types to avoid RuntimeErrors
doc_embeddings = model.encode(documents).astype('float32')

# Step 4: Store in FAISS index
dimension = doc_embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)  # L2 distance (Euclidean)
index.add(doc_embeddings)

# Step 5: Query
query = "Why do LLMs hallucinate?"
query_embedding = model.encode([query]).astype('float32')

# Step 6: Retrieve top-k documents
k = 3
# index.search returns (distances, indices)
distances, indices = index.search(query_embedding, k)

# Flatten indices[0] to get the list of document IDs
retrieved_docs = [documents[i] for i in indices[0]]

print("--- Retrieved Context ---")
for i, doc in enumerate(retrieved_docs):
    # Printing distance to see how 'close' the match was (lower is better for L2)
    print(f"{i+1}. [Dist: {distances[0][i]:.4f}] {doc}")

# Step 7: Combine context + question (The RAG Prompt)
context = " ".join(retrieved_docs)
final_prompt = f"Context: {context}\n\nQuestion: {query}\n\nAnswer based on context:"

print("\n--- Final Prompt for LLM ---")
print(final_prompt)