# -*- coding: utf-8 -*-
"""Prompt engineering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14PP3_r3iS-otn8Cks0VJ2PoN4bLq7VAj
"""

!pip install groq

!pip install groq

from groq import Groq

client = Groq(api_key="MY API KEY")

def call_model(prompt):
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content


t1_prompt = "Is this headline misleading? Explain why: 'Scientists say chocolate cures all diseases'"

print(call_model(t1_prompt))

response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[
        {
            "role": "system",
            "content": "You are a careful analyst. Think step by step before answering. Break down the reasoning clearly before giving the final answer."
        },
        {
            "role": "user",
            "content": "Is this headline misleading? Explain why: 'Scientists say chocolate cures all diseases'"
        }
    ],
    temperature=0.7
)

print("T2 OUTPUT:\n", response.choices[0].message.content)

t3_prompt = "Is this headline misleading? Explain why: 'AI will replace all jobs by 2030'"

def call_model_var(prompt):
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {
                "role": "system",
                "content": "You are a critical thinker. Analyze the claim carefully and reason step-by-step before answering."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.9  # ↑ increase variation
    )
    return response.choices[0].message.content


outputs = [call_model_var(t3_prompt) for _ in range(3)]

for i, out in enumerate(outputs, 1):
    print(f"\nRun {i}:\n{out}")

# Function with temperature control
def call_model(prompt, temperature=0.7):
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {
                "role": "system",
                "content": "You are a rational analyst. Evaluate claims carefully and explain your reasoning."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=temperature
    )
    return response.choices[0].message.content


# T4 Prompt
t4_prompt = "Is this headline misleading? Explain why: 'Drinking coffee doubles your lifespan'"


# Temperature experiment loop
for temp in [0.0, 0.5, 1.0]:
    result = call_model(t4_prompt, temperature=temp)
    print(f"\n--- Temperature {temp} ---\n{result}")